- README.md
Please take a look, thanks for your time :smile:
Signed-off-by: Ce Gao <gaoce@caicloud.io>
> README: Add Katib in AutoML section

- README.md
Signed-off-by: Ce Gao <gaoce@caicloud.io>
> fix(nexus): Add paper for the system

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Huaizheng laoshi nb! : P
Pls refer to [here](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) about how to build a github template, the same as issue template.
> Template should be set inside .github

- README.md
> added MindSpore、MegEngine、Jittor to the project

- AutoML_system.md
> added transmogrifAI and angel automl to the AutoML Opensource Toolkit

- README.md
- [[Systems for AI (W'20)]](https://github.com/mosharaf/eecs598/tree/w20-ai)
- [[Mosharaf Chowdhury]](https://www.mosharaf.com/) 
- Summary: Key concepts and the state-of-the-art in practical, scalable, and fault-tolerant software systems for AI.
> add a seminar course from University of Michigan

- conference.md
ACM SIGCOMM 2020 Workshop on Network Meets AI & ML (NetAI 2020)
https://conferences.sigcomm.org/sigcomm/2020/workshop-netai.html
> add netai workshop 

- edge_system.md
> Add papers to edge system

- inference.md
- BaiduBench Github Link
- Nvidia Triton Inference Server Slides (DEEP INTO TRITS)
- AIBench Paper and Website Link
> ✨ feat: added some inference materials

- inference.md
- Cloudburst: Stateful Functions-as-a-Service. [\[Paper\]](https://arxiv.org/pdf/2001.04592.pdf) [\[GitHub\]](https://github.com/hydro-project/cloudburst)
- Vikram Sreekanti, Chenggang Wu, Xiayue Charles Lin, Johann Schleier-Smith, Joseph E. Gonzalez, Joseph M. Hellerstein, Alexey Tumanov
- VLDB 2020
- A stateful FaaS platform.
(1) feasibility of general-purpose stateful serverless computing. 
(2) Autoscaling via logical disaggregation of storage and compute, state management via physical 
colocation of caches with compute services.
(3) LDPC design pattern
Close #45
> Add cloudburst VLDB'20

- training.md
- Title: A Unified Architecture for Accelerating Distributed
DNN Training in Heterogeneous GPU/CPU Clusters [[Paper]](https://www.usenix.org/system/files/osdi20-jiang.pdf)
> add byteps paper

- note/Eurosys2021.md
> Fixed the EuroMLSys program link

- README.md
HI, I thought this title would be a great addition to your list of books. Thank you for your consideration.
- Trust in Machine Learning [[Website]](https://www.manning.com/books/trust-in-machine-learning) 
- Kush Varshney (*2021*)
- Summary: Trust in Machine Learning reveals the four principles of trustworthiness that humans and machines both share: accuracy, reliability, openness, and selflessness. You’ll master practical techniques for achieving trustworthiness as you explore real-world use cases drawn from author Kush Varshney’s extensive career, including a peer-to-peer lender and an automated résumé screening service.
You’ll learn how to handle the inevitable distribution shift between training and operating data, measure and mitigate bias and unfairness, and be robust to deliberate …
> Added Trust in Machine Learning

- README.md
Hi,
Stjepan from manning here. I thought these two contributions might be a good match for your list. Thank you for considering them.
Best,
- Title [[Paper]](link) [[GitHub]](link)
- Author (*conference(journal) year*)
- Summary:
> Added new book and video

- README.md
RT
- Title[[CS 329S: Machine Learning Systems Design]](https://stanford-cs329s.github.io/index.html)
- Author: [Chip Huyen](https://huyenchip.com/)
- Summary: This course aims to provide an iterative framework for developing real-world machine learning systems that are deployable, reliable, and scalable.
> [MRG] Doc : Add new course from Stanford

- README.md
- Title [[Paper]](link) [[GitHub]](link)
- Author (*conference(journal) year*)
- Summary:
> Add SIGCOMM as ML sys conference

- README.md
- Colossal-AI: A Unified Deep Learning System for Big Model Era [[GitHub]](https://github.com/hpcaitech/ColossalAI)[[Blog]](https://medium.com/@hpcaitech/train-18-billion-parameter-gpt-models-with-a-single-gpu-on-your-personal-computer-8793d08332dc)
- Summary: 
Colossal-AI integrates many efficient techniques like multi-dimensional tensor parallelism, sequence parallelism, heterogeneous memory management, etc.
By using Colossal-AI, we could help users to efficiently and quickly deploy large AI model training and inference, reducing large AI model budgets and scaling down the labor cost of learning and deployment.
Thank you for your review and look forward to your reply.
> Add Colossal-AI

- edge_system.md
RT. Please review. Thanks. 😄 
- Title [[Paper]](link) [[GitHub]](link)
- Author (*conference(journal) year*)
- Summary:
> [MRG] Fix the issue that the paper "NestDNN" miss url.

- federated_learning_system.md
Flower [[Github]](https://github.com/adap/flower) [[Website]](https://flower.dev/) [[Paper]](https://arxiv.org/abs/2007.14390)
Summary:
A unified approach to federated learning, analytics, and evaluation. Federate any workload, any ML framework, and any programming language.
> Add Flower to Federated Learning Systems

- README.md
- Title [[Website]](https://www.manning.com/books/distributed-machine-learning-patterns) [[GitHub]](https://github.com/terrytangyuan/distributed-ml-patterns)
- Author (*conference(journal) year*): Yuan Tang, Manning, 2023
- Summary: this book teaches you how to take machine learning models from your personal laptop to large distributed clusters. You’ll explore key concepts and patterns behind successful distributed machine learning systems, and learn technologies like TensorFlow, Kubernetes, Kubeflow, and Argo Workflows with real-world scenarios and hands-on projects.
> Add Distributed Machine Learning Patterns from Manning

- training.md
Add new sections and papers to training.
> add training papers

- README.md
Title Machine Learning Systems: Principles and Practices of Engineering Artificially Intelligent Systems [[Website]](https://mlsysbook.ai/)
Author: Vijay Janapa Reddi
Summary: This book is an extension of the CS249r course at Harvard University, taught by Prof. Vijay Janapa Reddi, and is the result of a collaborative effort involving students, professionals, and the broader community of AI practitioners
> mlsysbook added
